---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: list articles
      tags:
      - "/"
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
  "/api/v1/articles":
    get:
      summary: list articles
      tags:
      - Articles
      parameters:
      - name: status
        in: query
        schema:
          type: string
          enum:
          - unpublished
          - published
        description: 'To filter Article by status: published/unpublished'
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1856
                title: 'The Lord of the Rings: The Return of the King'
                body: May the Force be with you.
                created_at: '2022-12-31T15:46:51.268Z'
                author: Forest Kirlin
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1857
                title: Shutter Island
                body: Toto, I've got a feeling we're not in Kansas anymore.
                created_at: '2022-12-31T15:46:51.296Z'
                author: Stephan Koepp
                comments: []
    patch:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1858
                title: Rush
                body: Go ahead, make my day.
                created_at: '2022-12-31T15:46:51.313Z'
                author: Sandy Gorczany IV
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
    put:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1859
                title: The Matrix
                body: Greetings, programs!
                created_at: '2022-12-31T15:46:51.332Z'
                author: Carl Carter LLD
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
    delete:
      summary: delete article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
  "/api/v1/articles/{article_id}/tags/{id}":
    parameters:
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: tag_add article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                data: Tag 'bvb' added in Article Double Indemnity
  "/api/v1/authors":
    get:
      summary: list authors
      tags:
      - Authors
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 641
                created_at: '2022-12-19T10:18:36.036Z'
                updated_at: '2022-12-19T10:18:36.036Z'
                name: Odis Rowe Ret.
              - id: 696
                created_at: '2022-12-19T10:23:27.382Z'
                updated_at: '2022-12-19T10:23:27.382Z'
                name: Versie Moen IV
              - id: 657
                created_at: '2022-12-19T10:19:46.524Z'
                updated_at: '2022-12-19T10:19:46.524Z'
                name: Domingo Crist
              - id: 673
                created_at: '2022-12-19T10:20:51.590Z'
                updated_at: '2022-12-19T10:20:51.590Z'
                name: Evonne Kemmer
              - id: 618
                created_at: '2022-12-19T10:17:30.824Z'
                updated_at: '2022-12-19T10:17:30.824Z'
                name: Salvatore Dach
              - id: 689
                created_at: '2022-12-19T10:21:29.591Z'
                updated_at: '2022-12-19T10:21:29.591Z'
                name: Allen Schumm
              - id: 634
                created_at: '2022-12-19T10:17:45.393Z'
                updated_at: '2022-12-19T10:17:45.393Z'
                name: Rep. Gary Bauch
    post:
      summary: create author
      tags:
      - Authors
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 2356
                created_at: '2022-12-31T15:46:51.434Z'
                updated_at: '2022-12-31T15:46:51.434Z'
                name: Les Reilly
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/authors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete author
      tags:
      - Authors
      responses:
        '200':
          description: successful
  "/api/v1/comments":
    get:
      summary: list comments
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 752
                body: I love the smell of napalm in the morning.
                status: unpublished
                author: Jefferey Quitzon
                created_at: '2022-12-31T15:46:51.498Z'
                article:
                  id: 1862
                  title: The Shining
                  body: Go ahead, make my day.
                  created_at: '2022-12-31T15:46:51.464Z'
                  author: Jefferey Quitzon
        '422':
          description: invalid request
          content:
            application/json:
              example:
                article:
                - must exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
  "/api/v1/comments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                comment:
                  id: 753
                  created_at: '2022-12-31T15:46:51.528Z'
                  updated_at: '2022-12-31T15:46:51.528Z'
                  body: May the Force be with you.
                  status: unpublished
                  article_id: 1863
                  author_id: 2360
                like: []
    patch:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 754
                body: All right, Mr. DeMille, I'm ready for my closeup.
                status: unpublished
                author: Amiee Stoltenberg
                created_at: '2022-12-31T15:46:51.554Z'
                article:
                  id: 1864
                  title: Rush
                  body: Here's looking at you, kid.
                  created_at: '2022-12-31T15:46:51.549Z'
                  author: Amiee Stoltenberg
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
    put:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 755
                body: I'm going to make him an offer he can't refuse.
                status: unpublished
                author: Rhett Green
                created_at: '2022-12-31T15:46:51.577Z'
                article:
                  id: 1865
                  title: Apocalypse Now
                  body: Go ahead, make my day.
                  created_at: '2022-12-31T15:46:51.572Z'
                  author: Rhett Green
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
  "/api/v1/likes":
    get:
      summary: list likes
      tags:
      - Likes
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create like
      tags:
      - Likes
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 264
                likeable_type: Article
                likeable_id: 1867
                created_at: '2022-12-31T15:46:51.638Z'
                updated_at: '2022-12-31T15:46:51.638Z'
                author_id: 2364
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author_id:
                  type: integer
                likeable_type:
                  type: string
                likeable_id:
                  type: integer
              required:
              - author_id
              - likeable_type
              - likeable_id
  "/api/v1/tags":
    get:
      summary: list tags
      tags:
      - Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create tag
      tags:
      - Tags
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 453
                name: hashtag
                created_at: '2022-12-31T15:46:51.654Z'
                updated_at: '2022-12-31T15:46:51.654Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/tags/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete tag
      tags:
      - Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
