---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/":
    get:
      summary: list articles
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
  "/api/v1/articles":
    get:
      summary: list articles
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1482
                title: 'The Lord of the Rings: The Return of the King'
                body: Go ahead, make my day.
                created_at: '2022-12-19T16:39:18.913Z'
                author: Leta Altenwerth
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1483
                title: There Will Be Blood
                body: Go ahead, make my day.
                created_at: '2022-12-19T16:39:18.940Z'
                author: Cheryll Kemmer
                comments: []
    patch:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1484
                title: Donnie Darko
                body: I'm going to make him an offer he can't refuse.
                created_at: '2022-12-19T16:39:18.980Z'
                author: Linn Walker
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
    put:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1485
                title: Judgment at Nuremberg
                body: What we've got here is failure to communicate.
                created_at: '2022-12-19T16:39:19.003Z'
                author: Noe Kihn
                comments: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
              - status
    delete:
      summary: delete article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
  "/api/v1/articles/{article_id}/tags/{id}":
    parameters:
    - name: article_id
      in: path
      description: article_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: tag_add article
      tags:
      - Articles
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                data: Tag 'dli' added in Article Stalker
  "/api/v1/authors":
    get:
      summary: list authors
      tags:
      - Authors
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 641
                created_at: '2022-12-19T10:18:36.036Z'
                updated_at: '2022-12-19T10:18:36.036Z'
                name: Odis Rowe Ret.
              - id: 696
                created_at: '2022-12-19T10:23:27.382Z'
                updated_at: '2022-12-19T10:23:27.382Z'
                name: Versie Moen IV
              - id: 657
                created_at: '2022-12-19T10:19:46.524Z'
                updated_at: '2022-12-19T10:19:46.524Z'
                name: Domingo Crist
              - id: 673
                created_at: '2022-12-19T10:20:51.590Z'
                updated_at: '2022-12-19T10:20:51.590Z'
                name: Evonne Kemmer
              - id: 618
                created_at: '2022-12-19T10:17:30.824Z'
                updated_at: '2022-12-19T10:17:30.824Z'
                name: Salvatore Dach
              - id: 689
                created_at: '2022-12-19T10:21:29.591Z'
                updated_at: '2022-12-19T10:21:29.591Z'
                name: Allen Schumm
              - id: 634
                created_at: '2022-12-19T10:17:45.393Z'
                updated_at: '2022-12-19T10:17:45.393Z'
                name: Rep. Gary Bauch
    post:
      summary: create author
      tags:
      - Authors
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1885
                created_at: '2022-12-19T16:39:19.102Z'
                updated_at: '2022-12-19T16:39:19.102Z'
                name: Freddy Mraz Ret.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/authors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete author
      tags:
      - Authors
      responses:
        '200':
          description: successful
  "/api/v1/comments":
    get:
      summary: list comments
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 596
                body: Greetings, programs!
                status: unpublished
                author: Daisy Deckow
                created_at: '2022-12-19T16:39:19.167Z'
                article:
                  id: 1488
                  title: The Third Man
                  body: Here's looking at you, kid.
                  created_at: '2022-12-19T16:39:19.154Z'
                  author: Daisy Deckow
        '422':
          description: invalid request
          content:
            application/json:
              example:
                article:
                - must exist
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
  "/api/v1/comments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                comment:
                  id: 597
                  created_at: '2022-12-19T16:39:19.197Z'
                  updated_at: '2022-12-19T16:39:19.197Z'
                  body: You talking to me?
                  status: unpublished
                  article_id: 1489
                  author_id: 1889
                like: []
    patch:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 598
                body: Toto, I've got a feeling we're not in Kansas anymore.
                status: unpublished
                author: Sheldon Reinger
                created_at: '2022-12-19T16:39:19.221Z'
                article:
                  id: 1490
                  title: Heat
                  body: Greetings, programs!
                  created_at: '2022-12-19T16:39:19.217Z'
                  author: Sheldon Reinger
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
    put:
      summary: update comment
      tags:
      - Comments
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 599
                body: Greetings, programs!
                status: unpublished
                author: Ida Braun
                created_at: '2022-12-19T16:39:19.243Z'
                article:
                  id: 1491
                  title: Snatch
                  body: I'm going to make him an offer he can't refuse.
                  created_at: '2022-12-19T16:39:19.239Z'
                  author: Ida Braun
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: string
                article_id:
                  type: integer
                author_id:
                  type: integer
              required:
              - body
              - author_id
              - article_id
              - status
    delete:
      summary: delete comment
      tags:
      - Comments
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
  "/api/v1/likes":
    get:
      summary: list likes
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create like
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 202
                likeable_type: Article
                likeable_id: 1493
                created_at: '2022-12-19T16:39:19.301Z'
                updated_at: '2022-12-19T16:39:19.301Z'
                author_id: 1893
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author_id:
                  type: integer
                likeable_type:
                  type: string
                likeable_id:
                  type: integer
              required:
              - author_id
              - likeable_type
              - likeable_id
  "/api/v1/tags":
    get:
      summary: list tags
      tags:
      - Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: []
    post:
      summary: create tag
      tags:
      - Tags
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 360
                name: marfa
                created_at: '2022-12-19T16:39:19.317Z'
                updated_at: '2022-12-19T16:39:19.317Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/tags/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete tag
      tags:
      - Tags
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: ok
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
